# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrontPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(975, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.ScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScrollArea.sizePolicy().hasHeightForWidth())
        self.ScrollArea.setSizePolicy(sizePolicy)
        self.ScrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.ScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.ScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.ScrollArea.setWidgetResizable(True)
        self.ScrollArea.setObjectName("ScrollArea")
        self.MainPage = QtWidgets.QWidget()
        self.MainPage.setGeometry(QtCore.QRect(0, 0, 941, 900))
        self.MainPage.setMinimumSize(QtCore.QSize(0, 900))
        self.MainPage.setObjectName("MainPage")
        self.MenuBarWidget = QtWidgets.QWidget(self.MainPage)
        self.MenuBarWidget.setGeometry(QtCore.QRect(0, 0, 940, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MenuBarWidget.sizePolicy().hasHeightForWidth())
        self.MenuBarWidget.setSizePolicy(sizePolicy)
        self.MenuBarWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.MenuBarWidget.setBaseSize(QtCore.QSize(0, 0))
        self.MenuBarWidget.setStyleSheet("QWidget{\n"
"background-color:rgb(56,77,91);\n"
"}")
        self.MenuBarWidget.setObjectName("MenuBarWidget")
        self.CompanyLogo = QtWidgets.QLabel(self.MenuBarWidget)
        self.CompanyLogo.setGeometry(QtCore.QRect(0, 0, 131, 75))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.CompanyLogo.setFont(font)
        self.CompanyLogo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CompanyLogo.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.CompanyLogo.setTextFormat(QtCore.Qt.AutoText)
        self.CompanyLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.CompanyLogo.setObjectName("CompanyLogo")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.MenuBarWidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(130, 0, 781, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.MenuBar = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.MenuBar.setContentsMargins(0, 0, 0, 0)
        self.MenuBar.setSpacing(14)
        self.MenuBar.setObjectName("MenuBar")
        self.SearchArea = QtWidgets.QHBoxLayout()
        self.SearchArea.setContentsMargins(50, -1, 50, -1)
        self.SearchArea.setSpacing(0)
        self.SearchArea.setObjectName("SearchArea")
        self.SearchBar = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.SearchBar.setText("")
        self.SearchBar.setObjectName("SearchBar")
        self.SearchArea.addWidget(self.SearchBar)
        self.MenuBar.addLayout(self.SearchArea)
        self.LoginBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.LoginBtn.setStyleSheet("QPushButton{\n"
        "background-color:rgb(56,77,91);\n"
        "border:none;\n"
        "color: rgb(255, 255, 255);\n"
        "}\n"
        "\n"
        "QPushButton::hover{\n"
        "color: rgb(250, 207, 125);\n"
        "}")
        self.LoginBtn.setObjectName("LoginBtn")
        self.MenuBar.addWidget(self.LoginBtn)
        self.CartBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.CartBtn.setStyleSheet("QPushButton{\n"
"background-color:rgb(56,77,91);\n"
"border:none;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color: rgb(250, 207, 125);\n"
"}")
        self.CartBtn.setObjectName("CartBtn")
        self.MenuBar.addWidget(self.CartBtn)
        self.ForumBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.ForumBtn.setStyleSheet("QPushButton{\n"
"background-color:rgb(56,77,91);\n"
"border:none;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"color: rgb(250, 207, 125);\n"
"}")
        self.ForumBtn.setObjectName("ForumBtn")
        self.MenuBar.addWidget(self.ForumBtn)
        self.ScrollArea.setWidget(self.MainPage)
        self.gridLayout.addWidget(self.ScrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CompanyLogo.setText(_translate("MainWindow", "Spoiled Egg"))
        self.LoginBtn.setText(_translate("MainWindow", "Login/Registration"))
        self.CartBtn.setText(_translate("MainWindow", "Cart"))
        self.ForumBtn.setText(_translate("MainWindow", "Forum"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
