# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(976, 646)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.HomeBtn = QtWidgets.QPushButton(Form)
        self.HomeBtn.setGeometry(QtCore.QRect(380, 30, 211, 91))
        self.HomeBtn.setObjectName("HomeBtn")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(340, 130, 349, 451))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.LoginBox = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.LoginBox.setContentsMargins(0, 0, 0, 0)
        self.LoginBox.setObjectName("LoginBox")
        self.LoginLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.LoginLabel.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.LoginLabel.setFont(font)
        self.LoginLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LoginLabel.setObjectName("LoginLabel")
        self.LoginBox.addWidget(self.LoginLabel)
        self.EmailForm = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.EmailForm.setInputMethodHints(QtCore.Qt.ImhNone)
        self.EmailForm.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.EmailForm.setObjectName("EmailForm")
        self.LoginBox.addWidget(self.EmailForm)
        self.PasswordForm = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.PasswordForm.setText("")
        self.PasswordForm.setObjectName("PasswordForm")
        self.LoginBox.addWidget(self.PasswordForm)
        self.ContinueBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.ContinueBtn.setObjectName("ContinueBtn")
        self.LoginBox.addWidget(self.ContinueBtn)
        spacerItem = QtWidgets.QSpacerItem(266, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.LoginBox.addItem(spacerItem)
        self.NewAccountLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.NewAccountLabel.setMaximumSize(QtCore.QSize(16777215, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.NewAccountLabel.setFont(font)
        self.NewAccountLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.NewAccountLabel.setObjectName("NewAccountLabel")
        self.LoginBox.addWidget(self.NewAccountLabel)
        self.RegistrationBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.RegistrationBtn.setObjectName("RegistrationBtn")
        self.LoginBox.addWidget(self.RegistrationBtn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.HomeBtn.setText(_translate("Form", "home"))
        self.LoginLabel.setText(_translate("Form", "Log In                                                                     "))
        self.EmailForm.setText(_translate("Form", "gagwagwa"))
        self.EmailForm.setPlaceholderText(_translate("Form", "Email"))
        self.PasswordForm.setPlaceholderText(_translate("Form", "Password"))
        self.ContinueBtn.setText(_translate("Form", "Continue"))
        self.NewAccountLabel.setText(_translate("Form", "New to Spoiled_Egg?                                                        "))
        self.RegistrationBtn.setText(_translate("Form", "Create your Spoiled_Egg account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
