DROP DATABASE IF EXISTS SpoiledEgg;
CREATE DATABASE SpoiledEgg;
USE SpoiledEgg;

CREATE TABLE Spoiled_Users(
    ID INTEGER PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    EMAIL VARCHAR(512) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Phone_Number VARCHAR(13),
    USER_Type VARCHAR(255) NOT NULL
);

